services:
  - type: web
    name: portfolio-backend
    env: java
    plan: free
    rootDir: Backend
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/portfolio-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
